[[categories]]
name = "about-landscape-1"

[[categories.images]]
source = "https://live.staticflickr.com/4441/36399442180_7fd09c2f72_o.jpg"
caption = "The Bigăr Waterfall in Caraș-Severin"
source_name = "Guiseppe Milo, via Flickr"
source_link = "https://www.flickr.com/photos/giuseppemilo/36399442180"

[[categories.images]]
source = "https://upload.wikimedia.org/wikipedia/commons/6/62/Pelicans_at_the_Danube_Delta%2C_Romania.jpg"
caption = "Pelicans in the Danube Delta"
source_name = "Thepinkfluffy1211, via Wikimedia Commons"
source_link = "https://commons.wikimedia.org/wiki/File:Pelicans_at_the_Danube_Delta,_Romania.jpg"

[[categories]]
name = "about-landscape-2"

[[categories.images]]
source = "https://upload.wikimedia.org/wikipedia/commons/0/01/Alone_in_the_unspoilt_wilderness_%28Unsplash%29.jpg"
caption = "Ciucaș Peak in the Carpathian Mountains"
source_name = "David Marcu, via Wikimedia Commons"
source_link = "https://commons.wikimedia.org/wiki/File:Alone_in_the_unspoilt_wilderness_(Unsplash).jpg"

[[categories.images]]
source = "https://upload.wikimedia.org/wikipedia/commons/c/c2/Brasov_Square_Romania_%28137177011%29.jpeg"
caption = "The medieval city of Brașov"
source_name = "Cristi Mitan, via Wikimedia Commons"
source_link = "https://commons.wikimedia.org/wiki/File:Brasov_Square_Romania_(137177011).jpeg"

[[categories]]
name = "about-dracula"

[[categories.images]]
source="https://upload.wikimedia.org/wikipedia/commons/8/87/Bran-Castle-Transylvania-0101.jpg"
caption="Bran Castle (a.k.a. Dracula's Castle)"
source_name="Seradelaluz, via Wikimedia Commons"
source_link="https://commons.wikimedia.org/wiki/File:Bran-Castle-Transylvania-0101.jpg"

[[categories.images]]
source="https://upload.wikimedia.org/wikipedia/commons/6/68/Vlad_the_Impaler.jpg"
caption="Vlad the Impaler"
source_name="Banekondic1996, via Wikimedia Commons"
source_link="https://commons.wikimedia.org/wiki/File:Vlad_the_Impaler.jpg"

[[categories]]
name = "about-crafts"

[[categories.images]]
source="https://ich.unesco.org/img/photo/thumb/06509-HUG.jpg"
caption="Craftsmanship of Horezu ceramics"
source_name="Rodica Dinache, via CNCPCT/MCPN"
source_link="https://ich.unesco.org/en/RL/craftsmanship-of-horezu-ceramics-00610"

[[categories.images]]
source="https://upload.wikimedia.org/wikipedia/commons/d/d5/Henri_matisse%2C_la_camicetta_romena%2C_1940.jpg"
caption="La Blouse Roumaine (painting)"
source_name="Henri Matisse, via Wikimedia Commons"
source_link="https://commons.wikimedia.org/wiki/File:Henri_matisse,_la_camicetta_romena,_1940.jpg"

[[categories]]
name = "about-tradition"

[[categories.images]]
source="https://upload.wikimedia.org/wikipedia/commons/e/ec/Muzeul_Na%C8%9Bional_al_Satului_%E2%80%9EDimitrie_Gusti%E2%80%9D_1.jpg"
caption="Dimitrie Gusti National Village Museum"
source_name="CrisNYCa, via Wikimedia Commons"
source_link="https://commons.wikimedia.org/wiki/File:Muzeul_Na%C8%9Bional_al_Satului_%E2%80%9EDimitrie_Gusti%E2%80%9D_1.jpg"

[[categories.images]]
source="https://live.staticflickr.com/3541/3826555756_820b03cfc8_o.jpg"
caption="Monastery in Maramureș"
source_name="Gabi Abu, via Flickr"
source_link="https://www.flickr.com/photos/ragnarokr/3826555756"

[[categories]]
name = "about-food"

[[categories.images]]
source="https://upload.wikimedia.org/wikipedia/commons/2/2c/Traditionelle_rum%C3%A4nische_Kohlrouladen_mit_Polenta_%28Maisgrie%C3%9Fkugeln%29_%2847981417742%29.jpg"
caption="Sarmale with Polenta"
source_name="dronepicr, via Wikimedia Commons"
source_link="https://commons.wikimedia.org/wiki/File:Traditionelle_rum%C3%A4nische_Kohlrouladen_mit_Polenta_(Maisgrie%C3%9Fkugeln)_(47981417742).jpg"

[[categories.images]]
source="https://upload.wikimedia.org/wikipedia/commons/a/ae/Papanasi_cu_cirese.jpg"
caption="Papanași with cherry jam"
source_name="Nicubunu via Wikimedia Commons"
source_link="https://commons.wikimedia.org/wiki/File:Papanasi_cu_cirese.jpg"

[[categories]]
name = "about-bucharest"

[[categories.images]]
source="https://romania-photo-tours.com/wp-content/uploads/2019/11/Bucharest-Palace-of-the-Parliament.jpg"
caption="Palace of the Parliament"
source_name="Romania Photo Tours"
source_link="https://romania-photo-tours.com/gallery/"

[[categories]]
name = "about-bucharest-old-1"

[[categories.images]]
source="https://live.staticflickr.com/4521/24396923048_8fda4deaa5_b.jpg"
caption="Arcul de Triumf"
source_name="David Stanley via Flickr"
source_link="https://www.flickr.com/photos/davidstanleytravel/24396923048/"

[[categories.images]]
source="https://upload.wikimedia.org/wikipedia/commons/0/0b/Ateneo_Rumano%2C_Bucarest%2C_Ruman%C3%ADa%2C_2016-05-29%2C_DD_73.jpg"
caption="The Romanian Athenaeum"
source_name="Diego Delso via Wikimedia Commons"
source_link="https://commons.wikimedia.org/wiki/File:Ateneo_Rumano,_Bucarest,_Ruman%C3%ADa,_2016-05-29,_DD_73.jpg"

[[categories]]
name = "about-bucharest-old-2"

[[categories.images]]
source="https://upload.wikimedia.org/wikipedia/commons/d/d0/Palacio_CEC%2C_Bucarest%2C_Ruman%C3%ADa%2C_2016-05-29%2C_DD_65.jpg"
caption="CEC Palace"
source_name="Diego Delso via Wikimedia Commons"
source_link="https://commons.wikimedia.org/wiki/File:Palacio_CEC,_Bucarest,_Ruman%C3%ADa,_2016-05-29,_DD_65.jpg"

[[categories.images]]
source="https://live.staticflickr.com/4032/4296739712_eddc7815d9_k.jpg"
caption="Stavropoleos Monastery"
source_name="Klearchos Kapoutsis via Flickr"
source_link="https://www.flickr.com/photos/klearchos/4296739712"

[[categories]]
name = "about-bucharest-new"

[[categories.images]]
source="https://live.staticflickr.com/65535/53688274379_fb4487b654_k.jpg"
caption="Smârdan Street"
source_name="Jorge Franganillo via Flickr"
source_link="https://www.flickr.com/photos/franganillo/53688274379/"

[[categories.images]]
source="https://upload.wikimedia.org/wikipedia/commons/6/63/Pasajul_Macca-_Villacrosse%2C_Bucure%C8%99ti.jpg"
caption="Macca-Villacrosse Passage"
source_name="Nicubunu via Wikimedia Commons"
source_link="https://commons.wikimedia.org/wiki/File:Pasajul_Macca-_Villacrosse,_Bucure%C8%99ti.jpg"

[[categories.images]]
source="https://upload.wikimedia.org/wikipedia/commons/7/72/55_Strada_Lipscani%2C_Bucharest_%2805%29.jpg"
caption="Cărturești Carusel Bookstore"
source_name="Neoclassicism Enthusiast via Wikimedia Commons"
source_link="https://commons.wikimedia.org/wiki/File:55_Strada_Lipscani,_Bucharest_(05).jpg"

[[categories]]
name = "past-volunteers"

[[categories.images]]
source="/volunteers/volunteers_iol2025.jpg"
caption="Volunteers at IOL 2025 Taipei"

[[categories.images]]
source="/volunteers/volunteers_iol2024.jpg"
caption="Volunteers at IOL 2024 Brasília"

[[categories]]
name = "registration-fees"

[[categories.images]]
source="/registration/Fees_RO.png"
caption=""