[[person]]
name="Paul Helmer"
role="Chair, Finance"
photo="loc/PH.jpeg"

[[person]]
name="Valentina Cojocaru"
role="Accommodation"
photo="loc/VC.jpeg"

[[person]]
name="Roxana Preda"
role="Venue, Logistics"
photo="loc/RP.jpg"

[[person]]
name="Vlad Neac»ôu"
role="Public Relations"
photo="loc/VN.jpeg"

[[person]]
name="Mihai Bratu"
role="Technology"
photo="loc/MB.jpeg"

[[person]]
name="Tamara Ivanof"
role="User Experience"
photo="loc/ETI.jpg"