[[person]]
name="Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

[[person]]
name="Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

[[person]]
name="Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

[[person]]
name="Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

[[person]]
name="Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

[[person]]
name="Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

[[person]]
name="Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

[[person]]
name="Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

[[person]]
name="Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

[[person]]
name="Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

[[person]]
name="Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

[[person]]
name="Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

[[person]]
name="Lorem Ipsum Lorem Ipsum Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

[[person]]
name="Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

[[person]]
name="Lorem Ipsum"
role="Dolor"
bio="Sit amet"
photo="loc/LI.JPG"

